import keyMirror from 'keymirror';

export default keyMirror({
    ADD_HIGHLIGHTED_ORBITAL: null,
    CAMERA_PANNED: null,
    MODAL_ACTIVE: null,
    REMOVE_HIGHLIGHTED_ORBITAL: null,
    SCALE_CHANGE: null,
    SETTINGS_ACTIVE: null,
    SET_ACTIVE_ORBITAL: null,
    SET_CAMERA_ORBIT: null,
    SET_LABEL_TEXT: null,
    SET_ORBITAL_DATA: null,
    SET_PAGE_TEXT: null,
    SET_PERCENT_LOADED: null,
    SET_PLAYING: null,
    SET_POSITION: null,
    SET_RELEASED: null,
    SET_TEXTURE_LOADED: null,
    SET_TIME: null,
    SET_TOUCHED: null,
    SET_UI_CONTROLS: null,
    SET_VOLUME: null,
    SHOW_LABEL: null,
    SPEED_CHANGE: null,
    TIME_OFFSET_CHANGE: null,
    TOUR_COMPLETED: null,
    TOUR_SKIPPED: null,
    ZOOM_CHANGE: null
});
